name: Mirror to GitLab

on:
  push:
    branches:
      - main  # Change this to the branch you want to mirror

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitHub repository (Full Clone)
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Ensures a full clone instead of a shallow one

      - name: Mirror to GitLab
        env:
          GITLAB_URL: "gitlab.com/rakigeneric/rakigeneric-keycloak-custom-theme.git"
          GITLAB_TOKEN: ${{ secrets.GITLAB_TOKEN }}
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"

          git remote add gitlab "https://rakesh-core:${GITLAB_TOKEN}@${GITLAB_URL}"
          
          git push --force --all gitlab
          
          # Push all tags
          git push --force --tags gitlab